name: Test2

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]  
  schedule:
    - cron: "0 0 * * *"  # nightly run

jobs:
  build:
    uses: mpg-age-bioinformatics/jawm/.github/workflows/modules.webhook.yaml@main
    secrets: inherit