name: apptainer

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # nightly run

jobs:
  hpc-sim:
    name: Simulated HPC Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ">=3.10"

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.JAWM_BIOINFORMATICS_KEY }}

      - name: Add GitHub to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Install jawm
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          python -m pip install --upgrade pip
          pip install git+ssh://git@github.com/mpg-age-bioinformatics/jawm.git

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl jq

      - name: Install Apptainer from official release (robust)
        run: |
          echo "Fetching latest Apptainer .deb..."
          RELEASE_API="https://api.github.com/repos/apptainer/apptainer/releases/latest"

          # Get all .deb assets and pick the stable one (exclude 'dbgsym' and 'trixie+')
          URL=$(curl -s $RELEASE_API | jq -r '.assets[] | .browser_download_url' \
            | grep -E 'apptainer_[0-9].*amd64\.deb$' \
            | grep -v 'dbgsym' \
            | grep -v 'trixie' \
            | head -n 1)

          if [ -z "$URL" ]; then
            echo "⚠️ No valid .deb found in latest release. Falling back to 1.3.2."
            URL="https://github.com/apptainer/apptainer/releases/download/v1.3.2/apptainer_1.3.2_amd64.deb"
          fi

          echo "Downloading: $URL"
          wget -q "$URL" -O apptainer.deb
          sudo apt-get install -y ./apptainer.deb
          apptainer --version

      - name: Verify installations
        run: |
          echo "=== Versions ==="
          apptainer --version

      - name: Build Apptainer container
        run: |
          echo "Bootstraping Apptainer container..."
          cat << 'EOF' > container.def
          Bootstrap: docker
          From: ubuntu:22.04
          %post
              apt-get update && apt-get install -y python3
              echo "Hello from Apptainer container!"
          %runscript
              echo "Running container with $(python3 --version)"
          EOF

          sudo apptainer build mycontainer.sif container.def
          
      - name: Submit job that uses Apptainer
        run: |
          echo '#!/bin/bash' > job.sh
          echo 'echo "=== SLURM JOB START ==="' >> job.sh
          echo 'apptainer run mycontainer.sif' >> job.sh
          echo 'echo "=== SLURM JOB END ==="' >> job.sh
          chmod +x job.sh
          ./job.sh

      - name: Run jawm
        run: |
          jawm-test -p system -j local -t ./test/apptainer.txt

      - name: Succeeded
        if: success()
        run: echo "✅ test.py succeeded!" 

      - name: Slack Failure Notification
        if: failure() # skip during local actions testing
        run: |
          echo "❌ Job failed!" && \
          generate_post_data()
          {
            cat << EOF
          {
            "text": "❌ *${GITHUB_REPOSITORY##*/}@$(echo $GITHUB_SHA | cut -c 1-8)* test FAILED\n<https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}|View Run>"
          }
          EOF
          }
          curl -H "Content-Type: application/json" -X POST -d "$(generate_post_data)" ${{ secrets.SLACK_JAWM_WEBHOOK }}

      - name: Cleanup
        if: always()
        run: |
          echo "Cleaning up temporary Slurm files..."
          sudo pkill slurmctld || true
          rm -rf container.def mycontainer.sif job.sh /tmp/slurm-state /tmp/slurmd
          echo "✅ Simulation complete."
