name: Test2

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * *"  # nightly run

jobs:
  build:
    uses: mpg-age-bioinformatics/jawm/.github/workflows/modules.webhook.yaml@main
    secrets: inherit