name: Test

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    # GitHub cron is UTC. 06:00 Berlin = 04:00 UTC in summer, 05:00 UTC in winter.
    - cron: "30 4 * * *"

jobs:
  build:
    uses: mpg-age-bioinformatics/jawm/.github/workflows/modules.webhook.yaml@main
    secrets: inherit