name: Test module

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    # Run every night at midnight UTC
    - cron: "0 0 * * *"

jobs:
  build:
    uses: mpg-age-bioinformatics/jawm_demo/.github/workflows/reference.test.yaml@main
    secrets:
      JAWM_BIOINFORMATICS_KEY: ${{ secrets.JAWM_BIOINFORMATICS_KEY }}
      SLACK_JAWM_WEBHOOK: ${{ secrets.SLACK_JAWM_WEBHOOK }}
